name: Release (build + assets + npm)

on:
  push:
    tags:
      - 'v*.*.*'   # e.g., v1.2.3

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # create/update GitHub Releases
      id-token: write   # required for `npm publish --provenance` (optional, recommended)

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm install
        # Use `npm ci` ONLY if you decide to commit package-lock.json

      - name: Verify tag matches package.json version
        run: |
          PKG_VERSION=$(node -p "require('./package.json').version")
          TAG_VERSION="${GITHUB_REF_NAME#v}"
          echo "package.json: $PKG_VERSION"
          echo "git tag:       $TAG_VERSION"
          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: tag (v$TAG_VERSION) does not match package.json version ($PKG_VERSION)"
            exit 1
          fi

      - name: Build (ESM + UMD)
        run: npm run build

      - name: Minify
        run: npm run build:min

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**
          generate_release_notes: true

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance
        # If you don't want provenance, drop the flag and the id-token permission